LOG_STEP_IN "- Setting up libnfc-nci configuration"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/etc/libnfc-nci-NXP_SN100U.conf" 0 0 644 "u:object_r:system_file:s0"
LOG "- Renaming /system/system/etc/libnfc-nci-NXP_SN100U.conf to /system/system/etc/libnfc-nci-sn110t.conf"
EVAL "mv \"$WORK_DIR/system/system/etc/libnfc-nci-NXP_SN100U.conf\" \"$WORK_DIR/system/system/etc/libnfc-nci-sn110t.conf\""
SET_METADATA "system" "system/etc/libnfc-nci-sn110t.conf" 0 0 644 "u:object_r:system_file:s0"

ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/etc/libnfc-nci-SLSI.conf" 0 0 644 "u:object_r:system_file:s0"
LOG "- Renaming /system/system/etc/libnfc-nci-SLSI.conf to /system/system/etc/libnfc-nci-s3fwrn5.conf"
EVAL "mv \"$WORK_DIR/system/system/etc/libnfc-nci-SLSI.conf\" \"$WORK_DIR/system/system/etc/libnfc-nci-s3fwrn5.conf\""
SET_METADATA "system" "system/etc/libnfc-nci-s3fwrn5.conf" 0 0 644 "u:object_r:system_file:s0"
LOG_STEP_OUT

LOG "- Patching /vendor/etc/init/init.nfc.samsung.rc"
EVAL "echo \"\" >> \"$WORK_DIR/vendor/etc/init/init.nfc.samsung.rc\""
EVAL "echo \"on property:ro.boot.hardware.sku=\\\"\\\"\" >> \"$WORK_DIR/vendor/etc/init/init.nfc.samsung.rc\""
EVAL "echo \"    setprop ro.boot.hardware.sku \\\"s3fwrn5\\\"\" >> \"$WORK_DIR/vendor/etc/init/init.nfc.samsung.rc\""
EVAL "echo \"\" >> \"$WORK_DIR/vendor/etc/init/init.nfc.samsung.rc\""
EVAL "echo \"on property:ro.boot.nfc.feature.chipname=\\\"\\\"\" >> \"$WORK_DIR/vendor/etc/init/init.nfc.samsung.rc\""
EVAL "echo \"    setprop ro.boot.nfc.feature.chipname \\\"SLSI\\\"\" >> \"$WORK_DIR/vendor/etc/init/init.nfc.samsung.rc\""
EVAL "echo \"\" >> \"$WORK_DIR/vendor/etc/init/init.nfc.samsung.rc\""
EVAL "echo \"on property:ro.boot.product.hardware.sku=\\\"\\\"\" >> \"$WORK_DIR/vendor/etc/init/init.nfc.samsung.rc\""
EVAL "echo \"    setprop ro.boot.product.hardware.sku \\\"s3fwrn5\\\"\" >> \"$WORK_DIR/vendor/etc/init/init.nfc.samsung.rc\""
EVAL "echo \"\" >> \"$WORK_DIR/vendor/etc/init/init.nfc.samsung.rc\""
EVAL "echo \"on property:ro.vendor.nfc.feature.chipname=\\\"\\\"\" >> \"$WORK_DIR/vendor/etc/init/init.nfc.samsung.rc\""
EVAL "echo \"    setprop ro.vendor.nfc.feature.chipname \\\"SLSI\\\"\" >> \"$WORK_DIR/vendor/etc/init/init.nfc.samsung.rc\""
