LOG_STEP_IN "- Replacing Hotword"
DELETE_FROM_WORK_DIR "product" "priv-app/HotwordEnrollmentOKGoogleEx4CORTEXM55"
DELETE_FROM_WORK_DIR "product" "priv-app/HotwordEnrollmentXGoogleEx4CORTEXM55"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "product" "priv-app/HotwordEnrollmentOKGoogleEx4HEXAGON/HotwordEnrollmentOKGoogleEx4HEXAGON.apk" 0 0 644 "u:object_r:system_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "product" "priv-app/HotwordEnrollmentXGoogleEx4HEXAGON/HotwordEnrollmentXGoogleEx4HEXAGON.apk" 0 0 644 "u:object_r:system_file:s0"
LOG_STEP_OUT

LOG_STEP_IN "- Fixing BT audio"
DELETE_FROM_WORK_DIR "system" "system/apex/com.android.bt.apex"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/apex/com.android.bt.apex" 0 0 644 "u:object_r:system_file:s0"
LOG_STEP_OUT

LOG_STEP_IN "- Replacing GameDriver"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/priv-app/GameDriver-SM8550/GameDriver-SM8550.apk" 0 0 644 "u:object_r:system_file:s0"
LOG_STEP_OUT

LOG_STEP_IN "- Adding stock WFD blobs"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/bin/insthk" 0 2000 755 "u:object_r:insthk_exec:s0"
DELETE_FROM_WORK_DIR "system" "system/lib64/libhdcp_client_aidl.so"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/libhdcp2.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/libstagefright_hdcp.so" 0 0 644 "u:object_r:system_lib_file:s0"
DELETE_FROM_WORK_DIR "system" "system/lib64/vendor.samsung.hardware.security.hdcp.wifidisplay-V2-ndk.so"
LOG_STEP_OUT

LOG_STEP_IN "- Adding stock hwui blobs"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib/libhwui.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/libhwui.so" 0 0 644 "u:object_r:system_lib_file:s0"
LOG_STEP_OUT

LOG_STEP_IN "- Adding HIDL face biometrics libs"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/android.hardware.biometrics.face@1.0.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/vendor.samsung.hardware.biometrics.face@2.0.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/vendor.samsung.hardware.biometrics.face@3.0.so" 0 0 644 "u:object_r:system_lib_file:s0"
LOG_STEP_OUT

LOG_STEP_IN "- Adding QSEECOM blobs"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/bin/qseecomd" 0 0 755 "u:object_r:tee_exec:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/bin/hw/vendor.qti.hardware.qseecom@1.0-service" 0 0 755 "u:object_r:hal_drm_default_exec:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib/libQSEEComAPI.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib/com.qti.qseeaon.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib/com.qti.qseeutils.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib/vendor.qti.hardware.qseecom@1.0.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib/hw/vendor.qti.hardware.qseecom@1.0-impl.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libQSEEComAPI.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/com.qti.qseeaon.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/com.qti.qseeutils.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/vendor.qti.hardware.qseecom@1.0.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/hw/vendor.qti.hardware.qseecom@1.0-impl.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/etc/init/qseecomd.rc" 0 0 644 "u:object_r:vendor_configs_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc" 0 0 644 "u:object_r:vendor_configs_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system_ext" "system_ext/lib/libQSEEComAPI_system.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system_ext" "system_ext/lib/vendor.qti.hardware.qseecom@1.0.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system_ext" "system_ext/lib/vendor.qti.hardware.qseecom-V1-ndk.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system_ext" "system_ext/lib64/libQSEEComAPI_system.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system_ext" "system_ext/lib64/vendor.qti.hardware.qseecom@1.0.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system_ext" "system_ext/lib64/vendor.qti.hardware.qseecom-V1-ndk.so" 0 0 644 "u:object_r:system_lib_file:s0"
LOG_STEP_OUT

LOG_STEP_IN "- Adding VaultKeeper blobs"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/bin/vaultkeeperd" 0 0 755 "u:object_r:vaultkeeper_exec:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/bin/vendor.samsung.hardware.security.vaultkeeper@2.0-service" 0 0 755 "u:object_r:hal_vaultkeeper_default_exec:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/vendor.samsung.hardware.security.vaultkeeper@2.0.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/etc/init/vaultkeeper_common.rc" 0 0 644 "u:object_r:vendor_configs_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/etc/vintf/manifest/vaultkeeper_manifest.xml" 0 0 644 "u:object_r:vendor_configs_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib/vendor.samsung.hardware.security.vaultkeeper@2.0.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/vendor.samsung.hardware.security.vaultkeeper@2.0.so" 0 0 644 "u:object_r:system_lib_file:s0"
LOG_STEP_OUT

LOG_STEP_IN "- Adding VexFwk (Video Expert Framework) blobs"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib/libandroid.vexfwk.samsung.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib/libcommon-jni.vexfwk.samsung.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib/libimgproc.vexfwk.samsung.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib/libmetadata.vexfwk.samsung.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib/libndk.vexfwk.samsung.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib/libruntime.vexfwk.samsung.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib/libsdk-v2-jni.vexfwk.samsung.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib/vexfwk_service_aidl-ndk.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/libandroid.vexfwk.samsung.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/libcommon-jni.vexfwk.samsung.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/libimgproc.vexfwk.samsung.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/libmetadata.vexfwk.samsung.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/libndk.vexfwk.samsung.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/libruntime.vexfwk.samsung.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/libsdk-v2-jni.vexfwk.samsung.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/lib64/vexfwk_service_aidl-ndk.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/framework/vexfwk_service_lib.jar" 0 0 644 "u:object_r:system_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/etc/permissions/vexfwk_service_lib.xml" 0 0 644 "u:object_r:system_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/etc/public.libraries-vexfwk.samsung.txt" 0 0 644 "u:object_r:system_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "system" "system/priv-app/vexfwk_service/vexfwk_service.apk" 0 0 644 "u:object_r:system_file:s0"
LOG_STEP_OUT

LOG_STEP_IN "- Adding SNAP (AI/Neural Processing) blobs"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/bin/hw/vendor.samsung.hardware.snap-service" 0 0 755 "u:object_r:hal_snap_default_exec:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/bin/hw/vendor.samsung.hardware.securesnap-service" 0 0 755 "u:object_r:hal_snap_default_exec:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/bin/adsprpcd" 0 2000 755 "u:object_r:adsprpcd_exec:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/bin/cdsprpcd" 0 2000 755 "u:object_r:cdsprpcd_exec:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libadsprpc.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libadsp_default_listener.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libsnap_compute.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libsnap_compute_secure.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libsnap_compute_wrapper.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libsnap_compute_wrapper_secure.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libsnap_qnn.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libsnap_vndk.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libsnap_vndk_secure.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libsnaplite_native.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libsnaplite_native_secure.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libsnaplite_wrapper.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libsnaplite_wrapper_secure.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/libsnapmw.so" 0 0 644 "u:object_r:vendor_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/lib64/vendor.samsung.hardware.snap-V1-ndk.so" 0 0 644 "u:object_r:vendor_file:s0"
LOG_STEP_OUT

LOG_STEP_IN "- Adding AIDL display composer"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/bin/hw/vendor.qti.hardware.display.composer-service" 0 2000 755 "u:object_r:hal_graphics_composer_default_exec:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/etc/init/vendor.qti.hardware.display.composer-service.rc" 0 0 644 "u:object_r:vendor_configs_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/etc/vintf/manifest/vendor.qti.hardware.display.composer-service.xml" 0 0 644 "u:object_r:vendor_configs_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/etc/snapdragon_color_libs_config.xml" 0 0 644 "u:object_r:vendor_configs_file:s0"
LOG_STEP_OUT

LOG_STEP_IN "- Adding memtrack service"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/bin/hw/vendor.qti.hardware.memtrack-service" 0 2000 755 "u:object_r:hal_memtrack_default_exec:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/etc/init/memtrack_qti.rc" 0 0 644 "u:object_r:vendor_configs_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "vendor" "vendor/etc/vintf/manifest/memtrack_qti.xml" 0 0 644 "u:object_r:vendor_configs_file:s0"
LOG_STEP_OUT

