# Copyright (c) 2026 JeyKul

	# OS
	TARGET_OS_SINGLE_SYSTEM_IMAGE="tqssi"
	TARGET_OS_BUILD_SYSTEM_EXT_PARTITION=false

	TARGET_PLATFORM_SDK_VERSION=33
	TARGET_PRODUCT_SHIPPING_API_LEVEL=30
	TARGET_BOARD_API_LEVEL=30

	# DYNAMIC PARTITIONS
   	TARGET_SUPER_PARTITION_SIZE=10292822016
	TARGET_QTI_DYNAMIC_PARTITIONS_SIZE=10288627712	
	SOURCE_SUPER_GROUP_NAME="qti_dynamic_partitions"

	# DVFS APP
	TARGET_DVFSAPP_CONFIG_DVFS_POLICY_FILENAME="dvfs_policy_sdm8250_xx"
	
	# LCD
	TARGET_LCD_CONFIG_HFR_MODE="2"
	TARGET_LCD_CONFIG_HFR_SUPPORTED_REFRESH_RATE="60,120"
	TARGET_LCD_CONFIG_SEAMLESS_BRT="89,91"
	TARGET_LCD_CONFIG_SEAMLESS_LUX="200,2500"
	TARGET_LCD_CONFIG_COLOR_WEAKNESS_SOLUTION="0"
	TARGET_LCD_CONFIG_CONTROL_AUTO_BRIGHTNESS="3"
	TARGET_LCD_CONFIG_HFR_DEFAULT_REFRESH_RATE="120"
	TARGET_COMMON_SUPPORT_DYN_RESOLUTION_CONTROL=false
	
	# CAMERA
	TARGET_CAMERA_SUPPORT_CAMERAX_EXTENSION=true
	TARGET_CAMERA_SUPPORT_CUTOUT_PROTECTION=false
	TARGET_CAMERA_SUPPORT_MASS_APP_FLAVOR=false
	TARGET_CAMERA_SUPPORT_SDK_SERVICE=false

	# AUDIO
	TARGET_AUDIO_CONFIG_RECORDALIVE_LIB_VERSION="07020"
	TARGET_AUDIO_SUPPORT_ACH_RINGTONE=false
	TARGET_AUDIO_SUPPORT_DUAL_SPEAKER=true
	TARGET_AUDIO_SUPPORT_VIRTUAL_VIBRATION=false

	# IF XL
	# LCD
	TARGET_LCD_SUPPORT_MDNIE_HW=false
	TARGET_COMMON_CONFIG_MDNIE_MODE="45073"
	TARGET_COMMON_SUPPORT_HDR_EFFECT=true
	# DVFS APP
	TARGET_DVFSAPP_CONFIG_SSRM_POLICY_FILENAME="siop_gts7xl_sm8250"
	# FINGERPRINT
	TARGET_FINGERPRINT_CONFIG_SENSOR="google_touch_display_optical,settings=3"

	# IF WIFI
	# RIL
	TARGET_RIL_SIM_CONFIG_MULTISIM_TRAYCOUNT="0"
	TARGET_RIL_SUPPORT_WATERPROOF_SIM_TRAY_MSG=false
	TARGET_COMMON_SUPPORT_EMBEDDED_SIM=false
	
	# WIFI
	# TODO: Check if these are actually correct...
	TARGET_WLAN_CONFIG_CONNECTION_PERSONALIZATION="0"
	TARGET_WLAN_CONFIG_CPU_CSTATE_DISABLE_THRESHOLD="100"
	TARGET_WLAN_CONFIG_DATA_ACTIVITY_AFFINITY_BOOSTER_THRESHOLD="0"
	TARGET_WLAN_CONFIG_DYNAMIC_SWITCH="0"
	TARGET_WLAN_CONFIG_L1SS_DISABLE_THRESHOLD="0"
	TARGET_WLAN_SUPPORT_80211AX=true
	TARGET_WLAN_SUPPORT_80211AX_6GHZ=false
	TARGET_WLAN_SUPPORT_APE_SERVICE=false
	TARGET_WLAN_SUPPORT_LOWLATENCY=false
	TARGET_WLAN_SUPPORT_MBO=true
	TARGET_WLAN_SUPPORT_MOBILEAP_5G_BASEDON_COUNTRY=false
	TARGET_WLAN_SUPPORT_MOBILEAP_6G=false
	TARGET_WLAN_SUPPORT_MOBILEAP_POWER_SAVEMODE=true
	TARGET_WLAN_SUPPORT_MOBILEAP_PRIORITIZE_TRAFFIC=false
	TARGET_WLAN_SUPPORT_MOBILEAP_WIFI_CONCURRENCY=false
	TARGET_WLAN_SUPPORT_MOBILEAP_WIFISHARING_LITE=false

	TARGET_WLAN_SUPPORT_MOBILEAP_DUALAP=false
	TARGET_WLAN_SUPPORT_MOBILEAP_OWE=false

	TARGET_WLAN_SUPPORT_SWITCH_FOR_INDIVIDUAL_APPS=true
	TARGET_WLAN_SUPPORT_TWT_CONTROL=false
	TARGET_WLAN_SUPPORT_WIFI_TO_CELLULAR=false

	# Boot device
	TARGET_OS_BOOT_DEVICE_PATH="/dev/block/by-name"
	TARGET_DISABLE_AVB_SIGNING=true