SET_PROP_IF_DIFF "vendor" "ro.security.fips.ux" "Disabled"

ADD_TO_WORK_DIR "a73xqxx" "system" "system/bin" 0 2000 751 "u:object_r:system_file:s0"
ADD_TO_WORK_DIR "dm1qkdiw" "system" "system/lib/libandroid_servers.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "a73xqxx" "system" "system/lib/libmdf.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "dm1qkdiw" "system" "system/lib64/libandroid_servers.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "a73xqxx" "system" "system/lib64/libepm.so" 0 0 644 "u:object_r:system_lib_file:s0"
ADD_TO_WORK_DIR "a73xqxx" "system" "system/lib64/libmdf.so" 0 0 644 "u:object_r:system_lib_file:s0"

DELETE_FROM_WORK_DIR "system" "system/app/BlockchainBasicKit"
DELETE_FROM_WORK_DIR "system" "system/bin/dualdard"
DELETE_FROM_WORK_DIR "system" "system/etc/init/dualdard.rc"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.hdmapp.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.kgclient.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.zt.framework.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/sysconfig/preinstalled-packages-com.samsung.android.coldwalletservice.xml"
DELETE_FROM_WORK_DIR "system" "system/framework/service-samsung-blockchain.jar"
DELETE_FROM_WORK_DIR "system" "system/lib/android.hardware.weaver@1.0.so"
DELETE_FROM_WORK_DIR "system" "system/lib/hidl_tlc_blockchain_comm_client.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libdualdar.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libepm.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libhermes_cred.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libkeyutils.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libknox_filemanager.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libpersona.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libtlc_blockchain_comm.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libtlc_blockchain_keystore.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libtlc_blockchain_direct_comm.so"
DELETE_FROM_WORK_DIR "system" "system/lib/vendor.samsung.hardware.tlc.blockchain@1.0.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/hidl_tlc_blockchain_comm_client.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libdualdar.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libtlc_blockchain_comm.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libtlc_blockchain_keystore.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libtlc_blockchain_direct_comm.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/vendor.samsung.hardware.tlc.blockchain@1.0.so"
DELETE_FROM_WORK_DIR "system" "system/priv-app/HdmApk"
DELETE_FROM_WORK_DIR "system" "system/priv-app/KnoxAIFrameworkApp"
DELETE_FROM_WORK_DIR "system" "system/priv-app/KnoxGuard"
DELETE_FROM_WORK_DIR "system" "system/priv-app/KnoxZtFramework"
