#
# Copyright (C) 2025 Salvo Giangreco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# UN1CA configuration file for Snapdragon devices (qssi)

# Galaxy S22 (Snapdragon) (One UI 8.0)
SOURCE_FIRMWARE="SM-S901E/INS/350999641234561"
SOURCE_EXTRA_FIRMWARES=()
SOURCE_PLATFORM_SDK_VERSION=36
SOURCE_PRODUCT_SHIPPING_API_LEVEL=31
SOURCE_BOARD_API_LEVEL=31
SOURCE_SUPER_GROUP_NAME="qti_dynamic_partitions"

# SEC Product Feature
SOURCE_AUDIO_CONFIG_RECORDALIVE_LIB_VERSION="08020"
SOURCE_AUDIO_SUPPORT_ACH_RINGTONE=true
SOURCE_AUDIO_SUPPORT_DUAL_SPEAKER=true
SOURCE_AUDIO_SUPPORT_VIRTUAL_VIBRATION=true
SOURCE_CAMERA_SUPPORT_CAMERAX_EXTENSION=true
SOURCE_CAMERA_SUPPORT_CUTOUT_PROTECTION=false
SOURCE_CAMERA_SUPPORT_MASS_APP_FLAVOR=false
SOURCE_CAMERA_SUPPORT_SDK_SERVICE=true
SOURCE_COMMON_CONFIG_MDNIE_MODE="65303"
SOURCE_COMMON_SUPPORT_DYN_RESOLUTION_CONTROL=false
SOURCE_COMMON_SUPPORT_EMBEDDED_SIM=true
SOURCE_COMMON_SUPPORT_HDR_EFFECT=true
SOURCE_DVFSAPP_CONFIG_DVFS_POLICY_FILENAME="dvfs_policy_sm8450_xx"
SOURCE_DVFSAPP_CONFIG_SSRM_POLICY_FILENAME="siop_r0q_sm8450"
SOURCE_FINGERPRINT_CONFIG_SENSOR="google_touch_display_ultrasonic"
SOURCE_LCD_CONFIG_COLOR_WEAKNESS_SOLUTION="3"
SOURCE_LCD_CONFIG_CONTROL_AUTO_BRIGHTNESS="5"
SOURCE_LCD_CONFIG_HFR_DEFAULT_REFRESH_RATE="120"
SOURCE_LCD_CONFIG_HFR_MODE="2"
SOURCE_LCD_CONFIG_HFR_SUPPORTED_REFRESH_RATE="24,10,30,48,60,96,120"
SOURCE_LCD_CONFIG_HFR_SUPPORTED_REFRESH_RATE_NS="60"
SOURCE_LCD_CONFIG_SEAMLESS_BRT="84,85"
SOURCE_LCD_CONFIG_SEAMLESS_LUX="200,1500"
SOURCE_LCD_SUPPORT_MDNIE_HW=true
SOURCE_SECURITY_CONFIG_ESE_CHIP_VENDOR="NXP"
SOURCE_SECURITY_CONFIG_ESE_COS_NAME="JCOP6.2U"
SOURCE_RIL_FEATURES="vzwcdmaless lracdmaless uscacgcdmaless xaacdmaless onebinary satellite_carrier"
SOURCE_RIL_SIM_CONFIG_MULTISIM_TRAYCOUNT="1"
SOURCE_RIL_SUPPORT_WATERPROOF_SIM_TRAY_MSG=true
SOURCE_WLAN_CONFIG_CONNECTION_PERSONALIZATION="1"
SOURCE_WLAN_CONFIG_CPU_CSTATE_DISABLE_THRESHOLD="100"
SOURCE_WLAN_CONFIG_CUSTOM_BACKOFF=""
SOURCE_WLAN_CONFIG_DATA_ACTIVITY_AFFINITY_BOOSTER_THRESHOLD="0"
SOURCE_WLAN_CONFIG_DYNAMIC_SWITCH="0"
SOURCE_WLAN_CONFIG_L1SS_DISABLE_THRESHOLD="0"
SOURCE_WLAN_SUPPORT_80211AX=true
SOURCE_WLAN_SUPPORT_80211AX_6GHZ=false
SOURCE_WLAN_SUPPORT_APE_SERVICE=true
SOURCE_WLAN_SUPPORT_LOWLATENCY=true
SOURCE_WLAN_SUPPORT_MBO=true
SOURCE_WLAN_SUPPORT_MOBILEAP_5G_BASEDON_COUNTRY=false
SOURCE_WLAN_SUPPORT_MOBILEAP_6G=false
SOURCE_WLAN_SUPPORT_MOBILEAP_OWE=false
SOURCE_WLAN_SUPPORT_MOBILEAP_POWER_SAVEMODE=true
SOURCE_WLAN_SUPPORT_MOBILEAP_PRIORITIZE_TRAFFIC=true
SOURCE_WLAN_SUPPORT_MOBILEAP_WIFI_CONCURRENCY=false
SOURCE_WLAN_SUPPORT_MOBILEAP_WIFISHARING_LITE=false
SOURCE_WLAN_SUPPORT_SWITCH_FOR_INDIVIDUAL_APPS=true
SOURCE_WLAN_SUPPORT_TWT_CONTROL=true
SOURCE_WLAN_SUPPORT_WIFI_TO_CELLULAR=true
