#
# Copyright (C) 2025 Salvo Giangreco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# TerracottaROM configuration file for Snapdragon tablet devices

case "$TARGET_CODENAME" in
    *wifi)
        # Galaxy Tab S9+ (WiFi) (One UI 7.0)
        SOURCE_FIRMWARE="SM-X810/EUX/R52W705QG4R"
        SOURCE_EXTRA_FIRMWARES=()
        SOURCE_PLATFORM_SDK_VERSION=36
        SOURCE_BOARD_API_LEVEL=34
        SOURCE_PRODUCT_SHIPPING_API_LEVEL=33
        SOURCE_HAS_SYSTEM_EXT=true
        SOURCE_SUPER_GROUP_NAME="qti_dynamic_partitions"

        # SEC Product Feature
        SOURCE_AUDIO_SUPPORT_ACH_RINGTONE=false
        SOURCE_AUDIO_SUPPORT_DUAL_SPEAKER=true
        SOURCE_AUDIO_SUPPORT_VIRTUAL_VIBRATION=false
        SOURCE_AUTO_BRIGHTNESS_TYPE="3"
        SOURCE_DVFS_CONFIG_NAME="dvfs_policy_default"
        SOURCE_ESE_CHIP_VENDOR="NXP"
        SOURCE_ESE_COS_NAME="JCOP6.3U"
        SOURCE_FINGERPRINT_CONFIG_SENSOR="google_touch_display_optical,settings=3,screen_off"
        SOURCE_LCD_SUPPORT_MDNIE_HW=true
        SOURCE_HAS_MASS_CAMERA_APP=false
        SOURCE_HAS_QHD_DISPLAY=false
        SOURCE_LCD_CONFIG_HFR_MODE="2"
        SOURCE_LCD_CONFIG_HFR_SUPPORTED_REFRESH_RATE="30,60,120"
        SOURCE_LCD_CONFIG_HFR_DEFAULT_REFRESH_RATE="120"
        SOURCE_HFR_SEAMLESS_BRT="84,91"
        SOURCE_HFR_SEAMLESS_LUX="200,2500"
        SOURCE_IS_ESIM_SUPPORTED=false
        SOURCE_MDNIE_SUPPORTED_MODES="65303"
        SOURCE_MDNIE_WEAKNESS_SOLUTION_FUNCTION="3"
        SOURCE_MULTI_MIC_MANAGER_VERSION="08020"
        SOURCE_DVFSAPP_CONFIG_DVFS_POLICY_FILENAME="dvfs_policy_default"
        SOURCE_DVFSAPP_CONFIG_SSRM_POLICY_FILENAME="siop_gts9pwifi_sm8550"
        SOURCE_SUPPORT_CUTOUT_PROTECTION=false
        SOURCE_CAMERA_SUPPORT_CAMERAX_EXTENSION=true
        SOURCE_CAMERA_SUPPORT_CUTOUT_PROTECTION=false
        SOURCE_CAMERA_SUPPORT_MASS_APP_FLAVOR=false
        SOURCE_CAMERA_SUPPORT_SDK_SERVICE=true
        SOURCE_COMMON_CONFIG_MDNIE_MODE="65303"
        SOURCE_COMMON_SUPPORT_DYN_RESOLUTION_CONTROL=false
        SOURCE_COMMON_SUPPORT_EMBEDDED_SIM=false
        SOURCE_LCD_CONFIG_COLOR_WEAKNESS_SOLUTION="3"
        SOURCE_LCD_CONFIG_CONTROL_AUTO_BRIGHTNESS="3"
        SOURCE_RIL_SIM_CONFIG_MULTISIM_TRAYCOUNT="0"
        SOURCE_RIL_SUPPORT_WATERPROOF_SIM_TRAY_MSG=false

        # TODO: Check if these are actually correct...
        # not sure on this one 100%
        SOURCE_WLAN_CONFIG_CONNECTION_PERSONALIZATION="0"
        ###
        
        SOURCE_WLAN_CONFIG_CPU_CSTATE_DISABLE_THRESHOLD="100"
        SOURCE_WLAN_CONFIG_DATA_ACTIVITY_AFFINITY_BOOSTER_THRESHOLD="0"

        SOURCE_WLAN_CONFIG_DYNAMIC_SWITCH="0"
        SOURCE_WLAN_CONFIG_L1SS_DISABLE_THRESHOLD="0"
        SOURCE_WLAN_SUPPORT_80211AX=true
        SOURCE_WLAN_SUPPORT_80211AX_6GHZ=true
        SOURCE_WLAN_SUPPORT_APE_SERVICE=true
        SOURCE_WLAN_SUPPORT_LOWLATENCY=true
        SOURCE_WLAN_SUPPORT_MBO=true
        SOURCE_WLAN_SUPPORT_MOBILEAP_5G_BASEDON_COUNTRY=false
        SOURCE_WLAN_SUPPORT_MOBILEAP_6G=false
        SOURCE_WLAN_SUPPORT_MOBILEAP_POWER_SAVEMODE=true
        # set to false for now v
        SOURCE_WLAN_SUPPORT_MOBILEAP_PRIORITIZE_TRAFFIC=false
        SOURCE_WLAN_SUPPORT_MOBILEAP_WIFI_CONCURRENCY=false
        SOURCE_WLAN_SUPPORT_MOBILEAP_WIFISHARING_LITE=false

        SOURCE_WLAN_SUPPORT_MOBILEAP_DUALAP=false
        SOURCE_WLAN_SUPPORT_MOBILEAP_OWE=false

        SOURCE_WLAN_SUPPORT_SWITCH_FOR_INDIVIDUAL_APPS=true
        # again unsure
        SOURCE_WLAN_SUPPORT_TWT_CONTROL=false
        SOURCE_WLAN_SUPPORT_WIFI_TO_CELLULAR=true
        ;;
    gts*)
        # Galaxy Tab S9+ (5G) (One UI 7.0)
        SOURCE_FIRMWARE="SM-X816B/EUX/350635071230543"
        SOURCE_EXTRA_FIRMWARES=()
        SOURCE_PLATFORM_SDK_VERSION=36
        SOURCE_BOARD_API_LEVEL=34
        SOURCE_PRODUCT_SHIPPING_API_LEVEL=33
        SOURCE_HAS_SYSTEM_EXT=true
        SOURCE_SUPER_GROUP_NAME="qti_dynamic_partitions"

        # SEC Product Feature
        SOURCE_AUDIO_SUPPORT_ACH_RINGTONE=false
        SOURCE_AUDIO_SUPPORT_DUAL_SPEAKER=true
        SOURCE_AUDIO_SUPPORT_VIRTUAL_VIBRATION=true
        SOURCE_AUTO_BRIGHTNESS_TYPE="5"
        SOURCE_DVFS_CONFIG_NAME="dvfs_policy_default"
        SOURCE_ESE_CHIP_VENDOR="NXP"
        SOURCE_ESE_COS_NAME="JCOP6.3U"
        SOURCE_FINGERPRINT_CONFIG_SENSOR="google_touch_display_ultrasonic"
        SOURCE_LCD_SUPPORT_MDNIE_HW=true
        SOURCE_HAS_MASS_CAMERA_APP=false
        SOURCE_HAS_QHD_DISPLAY=false
        SOURCE_LCD_CONFIG_HFR_MODE="2"
        SOURCE_LCD_CONFIG_HFR_SUPPORTED_REFRESH_RATE="30,60,120"
        SOURCE_LCD_CONFIG_HFR_DEFAULT_REFRESH_RATE="120"
        SOURCE_HFR_SEAMLESS_BRT="84,91"
        SOURCE_HFR_SEAMLESS_LUX="200,2500"
        SOURCE_IS_ESIM_SUPPORTED=false
        SOURCE_MDNIE_SUPPORTED_MODES="65303"
        SOURCE_MDNIE_WEAKNESS_SOLUTION_FUNCTION="3"
        SOURCE_MULTI_MIC_MANAGER_VERSION="08020"
        SOURCE_DVFSAPP_CONFIG_DVFS_POLICY_FILENAME="dvfs_policy_sm8550_xx"
        SOURCE_DVFSAPP_CONFIG_SSRM_POLICY_FILENAME="siop_gts9wifi_sm8550"
        SOURCE_SUPPORT_CUTOUT_PROTECTION=false
        SOURCE_CAMERA_SUPPORT_CAMERAX_EXTENSION=true
        SOURCE_CAMERA_SUPPORT_CUTOUT_PROTECTION=false
        SOURCE_CAMERA_SUPPORT_MASS_APP_FLAVOR=false
        SOURCE_CAMERA_SUPPORT_SDK_SERVICE=true
        SOURCE_COMMON_CONFIG_MDNIE_MODE="65303"
        SOURCE_COMMON_SUPPORT_DYN_RESOLUTION_CONTROL=false
        SOURCE_COMMON_SUPPORT_EMBEDDED_SIM=true
        SOURCE_LCD_CONFIG_COLOR_WEAKNESS_SOLUTION="3"
        SOURCE_LCD_CONFIG_CONTROL_AUTO_BRIGHTNESS="5"
        SOURCE_RIL_SIM_CONFIG_MULTISIM_TRAYCOUNT="1"
        SOURCE_RIL_SUPPORT_WATERPROOF_SIM_TRAY_MSG=true
        SOURCE_WLAN_CONFIG_CONNECTION_PERSONALIZATION="1"
        SOURCE_WLAN_CONFIG_CPU_CSTATE_DISABLE_THRESHOLD="100"
        SOURCE_WLAN_CONFIG_DATA_ACTIVITY_AFFINITY_BOOSTER_THRESHOLD="0"

        SOURCE_WLAN_CONFIG_DYNAMIC_SWITCH="0"
        SOURCE_WLAN_CONFIG_L1SS_DISABLE_THRESHOLD="0"
        SOURCE_WLAN_SUPPORT_80211AX=true
        SOURCE_WLAN_SUPPORT_80211AX_6GHZ=false
        SOURCE_WLAN_SUPPORT_APE_SERVICE=true
        SOURCE_WLAN_SUPPORT_LOWLATENCY=true
        SOURCE_WLAN_SUPPORT_MBO=true
        SOURCE_WLAN_SUPPORT_MOBILEAP_5G_BASEDON_COUNTRY=false
        SOURCE_WLAN_SUPPORT_MOBILEAP_6G=false
        SOURCE_WLAN_SUPPORT_MOBILEAP_POWER_SAVEMODE=true
        SOURCE_WLAN_SUPPORT_MOBILEAP_PRIORITIZE_TRAFFIC=true
        SOURCE_WLAN_SUPPORT_MOBILEAP_WIFI_CONCURRENCY=false
        SOURCE_WLAN_SUPPORT_MOBILEAP_WIFISHARING_LITE=false
        SOURCE_WLAN_SUPPORT_SWITCH_FOR_INDIVIDUAL_APPS=true
        SOURCE_WLAN_SUPPORT_TWT_CONTROL=true
        SOURCE_WLAN_SUPPORT_WIFI_TO_CELLULAR=true

        ;;
    *)
        echo "\"$TARGET_CODENAME\" is not a valid target."
        return 1
        ;;
esac