#
# Copyright (C) 2025 Salvo Giangreco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Platform configuration file for Qualcomm Snapdragon 730G devices (sm7150)
TARGET_BOARD_API_LEVEL=30

# Partitions
TARGET_BOOT_PARTITION_SIZE=67108864
TARGET_DTBO_PARTITION_SIZE=10485760
TARGET_SUPER_PARTITION_SIZE=8053063680
TARGET_SUPER_GROUP_NAME="qti_dynamic_partitions"
TARGET_QTI_DYNAMIC_PARTITIONS_SIZE=8048869376
TARGET_OS_SINGLE_SYSTEM_IMAGE="qssi"
TARGET_OS_FILE_SYSTEM_TYPE="erofs"
TARGET_OS_BUILD_SYSTEM_EXT_PARTITION=false
TARGET_DISABLE_AVB_SIGNING=true

# Sec Product Feature
TARGET_AUDIO_CONFIG_RECORDALIVE_LIB_VERSION="07010"
TARGET_AUDIO_SUPPORT_ACH_RINGTONE=false
TARGET_AUDIO_SUPPORT_VIRTUAL_VIBRATION=false
TARGET_CAMERA_SUPPORT_CAMERAX_EXTENSION=false
TARGET_CAMERA_SUPPORT_CUTOUT_PROTECTION=false
TARGET_CAMERA_SUPPORT_MASS_APP_FLAVOR=true
TARGET_CAMERA_SUPPORT_SDK_SERVICE=false
TARGET_COMMON_SUPPORT_DYN_RESOLUTION_CONTROL=false
TARGET_COMMON_SUPPORT_EMBEDDED_SIM=false
TARGET_COMMON_SUPPORT_HDR_EFFECT=true
TARGET_LCD_CONFIG_COLOR_WEAKNESS_SOLUTION="3"
TARGET_LCD_CONFIG_CONTROL_AUTO_BRIGHTNESS="3"
TARGET_LCD_CONFIG_HFR_DEFAULT_REFRESH_RATE="60"
TARGET_LCD_CONFIG_HFR_MODE="0"
TARGET_LCD_SUPPORT_MDNIE_HW=true

# RIL
TARGET_RIL_SIM_CONFIG_MULTISIM_TRAYCOUNT="1"
TARGET_RIL_SUPPORT_WATERPROOF_SIM_TRAY_MSG=false
TARGET_RIL_FEATURES="onebinary"

# WLAN
TARGET_WLAN_CONFIG_CONNECTION_PERSONALIZATION="0"
TARGET_WLAN_CONFIG_CPU_CSTATE_DISABLE_THRESHOLD="100"
TARGET_WLAN_CONFIG_DATA_ACTIVITY_AFFINITY_BOOSTER_THRESHOLD="0"
TARGET_WLAN_CONFIG_DYNAMIC_SWITCH="0"
TARGET_WLAN_CONFIG_L1SS_DISABLE_THRESHOLD="0"
TARGET_WLAN_SUPPORT_80211AX=true
TARGET_WLAN_SUPPORT_80211AX_6GHZ=false
TARGET_WLAN_SUPPORT_APE_SERVICE=false
TARGET_WLAN_SUPPORT_LOWLATENCY=false
TARGET_WLAN_SUPPORT_MBO=false
TARGET_WLAN_SUPPORT_MOBILEAP_5G_BASEDON_COUNTRY=false
TARGET_WLAN_SUPPORT_MOBILEAP_6G=false
TARGET_WLAN_SUPPORT_MOBILEAP_DUALAP=false
TARGET_WLAN_SUPPORT_MOBILEAP_OWE=false
TARGET_WLAN_SUPPORT_MOBILEAP_POWER_SAVEMODE=true
TARGET_WLAN_SUPPORT_MOBILEAP_PRIORITIZE_TRAFFIC=true
TARGET_WLAN_SUPPORT_MOBILEAP_WIFI_CONCURRENCY=true
TARGET_WLAN_SUPPORT_MOBILEAP_WIFISHARING_LITE=true
TARGET_WLAN_SUPPORT_SWITCH_FOR_INDIVIDUAL_APPS=true
TARGET_WLAN_SUPPORT_TWT_CONTROL=false
TARGET_WLAN_SUPPORT_WIFI_TO_CELLULAR=true
