# UN1CA floating_feature patch
# - Add deprecated features in the $DEPRECATED variable
# - Add features to ignore in the $BLACKLIST variable
# - Add default values for missing features in the $FALLBACK variable
# - Use target/$TARGET_CODENAME/sff.sh file to provide custom entries

DEPRECATED="
SEC_FLOATING_FEATURE_AUDIO_CONFIG_FMRADIO_EXTERNAL_DEVICE
SEC_FLOATING_FEATURE_AUDIO_CONFIG_VOLUMEMONITOR_PHASE
SEC_FLOATING_FEATURE_BATTERY_SUPPORT_WIRELESS_TX_5V_TA
SEC_FLOATING_FEATURE_BIXBY_SUPPORT_USERKWD_WAKEUP
SEC_FLOATING_FEATURE_COMMON_CONFIG_DEX_MODE
SEC_FLOATING_FEATURE_COMMON_CONFIG_DUAL_IMS
SEC_FLOATING_FEATURE_COMMON_SUPPORT_CONVENTIONAL_MODE
SEC_FLOATING_FEATURE_COMMON_SUPPORT_D2D_NUMBER_TRANSFER_SEND_ONLY
SEC_FLOATING_FEATURE_COMMON_SUPPORT_DEX_ON_PC
SEC_FLOATING_FEATURE_COMMON_SUPPORT_EMBEDDED_SIM
SEC_FLOATING_FEATURE_COMMON_SUPPORT_EPDG_CROSS_SIM
SEC_FLOATING_FEATURE_COMMON_SUPPORT_KNOX_DESKTOP
SEC_FLOATING_FEATURE_COMMON_SUPPORT_SAFETYCARE
SEC_FLOATING_FEATURE_COMMON_SUPPORT_SPEN_ALERT
SEC_FLOATING_FEATURE_FMRADIO_CONFIG_COMMON_SUPPORT_HYBRIDSEARCH
SEC_FLOATING_FEATURE_FMRADIO_REMOVE_AF_MENU
SEC_FLOATING_FEATURE_FRAMEWORK_CONFIG_EDGE_QUICKTOOLS_SCREEN_HEIGHT
SEC_FLOATING_FEATURE_FRAMEWORK_SUPPORT_AUTO_ROTATION_OF_SMARTWIDGET
SEC_FLOATING_FEATURE_FRAMEWORK_SUPPORT_EAGLE_EYE
SEC_FLOATING_FEATURE_GALLERY_CONFIG_COLOR_ENGINE_VERSION
SEC_FLOATING_FEATURE_GALLERY_SUPPORT_LOCATION_POI
SEC_FLOATING_FEATURE_LOCKSCREEN_SUPPORT_VIDEO_PLAY_RANDOM_POSITION
SEC_FLOATING_FEATURE_MMFW_CONFIG_SMART_MIRRORING_PACKAGE_NAME
SEC_FLOATING_FEATURE_MMFW_SUPPORT_AI_UPSCALER
SEC_FLOATING_FEATURE_MMFW_SUPPORT_MTK_SSM_SM_VIDEO
SEC_FLOATING_FEATURE_MMFW_SUPPORT_MUSIC_AUTO_RECOMMENDATION
SEC_FLOATING_FEATURE_SAIV_CONFIG_BEAUTY_FACE
SEC_FLOATING_FEATURE_SECURITY_SUPPORT_STRONGBOX_API
SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_S_PEN_HOVERING_N_DETACHMENT
SEC_FLOATING_FEATURE_SIP_CONFIG_STICKER_CONTENTS
SEC_FLOATING_FEATURE_SIP_SUPPORT_DIRECT_WRITING_ENABLE
SEC_FLOATING_FEATURE_WEATHER_SUPPORT_DETAIL_CITY_VIEW
SEC_FLOATING_FEATURE_WIFI_SUPPORT_ADPS
SEC_FLOATING_FEATURE_WLAN_SUPPORT_SECURE_WIFI
"

BLACKLIST="
SEC_FLOATING_FEATURE_AUDIO_CONFIG_ASSISTANT_SPEAKER_MAX_VOLUME
SEC_FLOATING_FEATURE_BIXBY_CONFIG_BARGEIN_PARAM_MODE
SEC_FLOATING_FEATURE_CAMERA_CONFIG_AI_DEFLICKER
SEC_FLOATING_FEATURE_CAMERA_CONFIG_MOIRE_REMOVAL
SEC_FLOATING_FEATURE_CAMERA_CONFIG_MOTIONPHOTO_DEFAULT_SOUND_TIMING
SEC_FLOATING_FEATURE_CAMERA_CONFIG_MOTIONPHOTO_DEFAULT_SOUND_TYPE
SEC_FLOATING_FEATURE_CAMERA_CONFIG_MYFILTER
SEC_FLOATING_FEATURE_CAMERA_CONFIG_STRIDE_OCR_VERSION
SEC_FLOATING_FEATURE_CAMERA_CONFIG_SUPERSTEADY_POPUP
SEC_FLOATING_FEATURE_CAMERA_CONFIG_VERSION_FILTER_PROVIDER
SEC_FLOATING_FEATURE_CAMERA_DOCUMENTSCAN_SOLUTIONS
SEC_FLOATING_FEATURE_CAMERA_SUPPORT_AI_HIGH_RESOLUTION_DRAFT_DOWNSCALE
SEC_FLOATING_FEATURE_CAMERA_SUPPORT_CONTROLLING_WATCH
SEC_FLOATING_FEATURE_CAMERA_SUPPORT_PRIVACY_TOGGLE
SEC_FLOATING_FEATURE_COMMON_CONFIG_AI_VERSION
SEC_FLOATING_FEATURE_COMMON_CONFIG_AWESOME_INTELLIGENCE
SEC_FLOATING_FEATURE_COMMON_CONFIG_EDGE
SEC_FLOATING_FEATURE_COMMON_CONFIG_MULTIMEDIA_EDITOR_PLUGIN_PACKAGES
SEC_FLOATING_FEATURE_COMMON_CONFIG_SMARTTUTOR_PACKAGES_PATH
SEC_FLOATING_FEATURE_COMMON_DISABLE_NATIVE_AI
SEC_FLOATING_FEATURE_COMMON_SUPPORT_AI_AGENT
SEC_FLOATING_FEATURE_COMMON_SUPPORT_DESKTOP_WINDOWING
SEC_FLOATING_FEATURE_COMMON_SUPPORT_LTW_REMOTE_APP
SEC_FLOATING_FEATURE_CONTEXTSERVICE_ENABLE_SURVEY_MODE
SEC_FLOATING_FEATURE_DWB_CONFIG_UNSUSPENDABLE_PACKAGE_NAME
SEC_FLOATING_FEATURE_FACTORY_CONFIG_PART_REPLACEMENT_HISTORY
SEC_FLOATING_FEATURE_FMRADIO_CONFIG_AVOID_REGION
SEC_FLOATING_FEATURE_FRAMEWORK_CONFIG_AOD_ITEM
SEC_FLOATING_FEATURE_FRAMEWORK_SUPPORT_PERSONALIZED_DATA_CORE
SEC_FLOATING_FEATURE_FRAMEWORK_SUPPORT_SMART_SUGGESTIONS_WIDGET
SEC_FLOATING_FEATURE_FRAMEWORK_SUPPORT_STACK_WIDGET_AUTO_ROTATION
SEC_FLOATING_FEATURE_GALLERY_CONFIG_IMAGE_TAGGER_VERSION
SEC_FLOATING_FEATURE_GALLERY_CONFIG_PBE
SEC_FLOATING_FEATURE_GALLERY_SUPPORT_SPC_LOCATION_POI
SEC_FLOATING_FEATURE_GALLERY_SUPPORT_STORYEDITOR
SEC_FLOATING_FEATURE_GENAI_SUPPORT_C2PA
SEC_FLOATING_FEATURE_GENAI_SUPPORT_IMAGE_CLIPPER
SEC_FLOATING_FEATURE_GENAI_SUPPORT_OBJECT_ERASER
SEC_FLOATING_FEATURE_GENAI_SUPPORT_REFLECTION_ERASER
SEC_FLOATING_FEATURE_GENAI_SUPPORT_SHADOW_ERASER
SEC_FLOATING_FEATURE_GENAI_SUPPORT_SMART_LASSO
SEC_FLOATING_FEATURE_GENAI_SUPPORT_SPOT_FIXER
SEC_FLOATING_FEATURE_GENAI_SUPPORT_STYLE_TRANSFER
SEC_FLOATING_FEATURE_GPS_CONFIG_SUPL_VENDOR
SEC_FLOATING_FEATURE_GRAPHICS_CONFIG_GAMEBOOSTER_MORE_HEAT
SEC_FLOATING_FEATURE_GRAPHICS_CONFIG_GAMEBOOSTER_SUICIDE_INTERVAL_MS
SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_3D_SURFACE_TRANSITION_FLAG
SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_GAMEBOOSTER_MANUAL_ROUTINE
SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_GAME_SERVER_POLICY_QUERIES
SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_RELUMINO_EFFECT_FLAG
SEC_FLOATING_FEATURE_HWR_CONFIG_RECOGNITION_SUPPORT
SEC_FLOATING_FEATURE_LAUNCHER_CONFIG_ANIMATION_TYPE
SEC_FLOATING_FEATURE_MSCH_SUPPORT_NLSEARCH
SEC_FLOATING_FEATURE_RIL_CONFIG_DM_OPERATOR
SEC_FLOATING_FEATURE_SAIV_SUPPORT_3DPHOTO
SEC_FLOATING_FEATURE_SMART_VIEW_APP_CAST_SUPPORTED
SEC_FLOATING_FEATURE_SYSTEMUI_CONFIG_EDGELIGHTING_FRAME_EFFECT
SEC_FLOATING_FEATURE_SYSTEM_SUPPORT_SCREEN_CURTAIN
SEC_FLOATING_FEATURE_VISION_CONFIG_IMAGE_TRANSLATION_OVERLAY_VERSION
SEC_FLOATING_FEATURE_VISION_SUPPORT_AI_MY_FAVORITE_CONTENTS
"

FALLBACK="
SEC_FLOATING_FEATURE_AUDIO_CONFIG_INTERPRETER=0
SEC_FLOATING_FEATURE_CAMERA_CONFIG_MOTIONPHOTO_CAPTURE_MODE=[[3,1]]
SEC_FLOATING_FEATURE_CAMERA_CONFIG_WINE_DETECTOR=OFF
SEC_FLOATING_FEATURE_CAMERA_GRAW_CONFIG_MFP_PIPELINE_MODE=V1
SEC_FLOATING_FEATURE_GALLERY_CONFIG_AI_EXPANSION=AI_Timelapse
SEC_FLOATING_FEATURE_GALLERY_CONFIG_PET_CLUSTER_VERSION=None
SEC_FLOATING_FEATURE_GENAI_SUPPORT_TIME_WEATHER_WALLPAPER=None
SEC_FLOATING_FEATURE_GRAPHICS_CONFIG_GAME_DEFAULT_FRAMERATE=${TARGET_LCD_CONFIG_HFR_DEFAULT_REFRESH_RATE//none/60}
SEC_FLOATING_FEATURE_LCD_CONFIG_AOD_BRIGHTNESS_ANIMATION=0
SEC_FLOATING_FEATURE_LCD_CONFIG_AOD_FULLSCREEN=0
SEC_FLOATING_FEATURE_LCD_CONFIG_HW_MDNIE=DDI
SEC_FLOATING_FEATURE_LCD_CONFIG_LOCAL_HBM=0
SEC_FLOATING_FEATURE_LCD_CONFIG_NATURAL_MODE_TYPE=0
SEC_FLOATING_FEATURE_LCD_CONFIG_PRIVACY_DISPLAY=0
SEC_FLOATING_FEATURE_LCD_CONFIG_VIVIDNESS=0
SEC_FLOATING_FEATURE_LCD_CONFIG_VIVIDPLUS=0
SEC_FLOATING_FEATURE_SAIV_CONFIG_ARDOODLE_LIB=IMG_PICKING
"

# [
APPLY_TARGET_FEATURE()
{
    local TARGET_FIRMWARE_PATH="$(cut -d "/" -f 1 -s <<< "$TARGET_FIRMWARE")_$(cut -d "/" -f 2 -s <<< "$TARGET_FIRMWARE")"

    local SOURCE_FILE="$WORK_DIR/system/system/etc/floating_feature.xml"
    local TARGET_FILE="$FW_DIR/$TARGET_FIRMWARE_PATH/system/system/etc/floating_feature.xml"

    local FEATURE
    local SOURCE_VALUE
    local TARGET_VALUE

    # Step 1: iterate through work_dir floating_feature.xml
    while IFS= read -r l; do
        [[ "$l" == *"xml"* ]] && continue
        [[ "$l" == *"SecFloatingFeatureSet"* ]] && continue
        [ ! "$l" ] && continue

        if [[ "$l" != "    <SEC_FLOATING_FEATURE_"*"</SEC_FLOATING_FEATURE_"*">" ]]; then
            ABORT "Malformed string in ${SOURCE_FILE//$SRC_DIR\//}: \"$l\""
        fi

        FEATURE="$(awk -F '<|>' '{print $2}' <<< "$l")"

        if grep -q -w "$FEATURE" <<< "$BLACKLIST"; then
            continue
        fi

        SOURCE_VALUE="$(GET_FLOATING_FEATURE_CONFIG "$SOURCE_FILE" "$FEATURE")"
        TARGET_VALUE="$(GET_FLOATING_FEATURE_CONFIG "$TARGET_FILE" "$FEATURE")"

        if [ ! "$TARGET_VALUE" ]; then
            TARGET_VALUE="$(cut -d "=" -f 2- < <(grep -w "$FEATURE" <<< "$FALLBACK"))"
        fi

        if [ ! "$TARGET_VALUE" ]; then
            SET_FLOATING_FEATURE_CONFIG "$FEATURE" --delete
        elif [[ "$SOURCE_VALUE" != "$TARGET_VALUE" ]]; then
            SET_FLOATING_FEATURE_CONFIG "$FEATURE" "$TARGET_VALUE"
        fi
    done < "$SOURCE_FILE"

    # Step 2: iterate through target floating_feature.xml
    while IFS= read -r l; do
        [[ "$l" == *"xml"* ]] && continue
        [[ "$l" == *"SecFloatingFeatureSet"* ]] && continue
        [ ! "$l" ] && continue

        if [[ "$l" != "    <SEC_FLOATING_FEATURE_"*"</SEC_FLOATING_FEATURE_"*">" ]]; then
            ABORT "Malformed string in ${TARGET_FILE//$SRC_DIR\//}: \"$l\""
        fi

        FEATURE="$(awk -F '<|>' '{print $2}' <<< "$l")"

        if grep -q -w "$FEATURE" <<< "$BLACKLIST"; then
            continue
        fi

        if ! grep -q -w "$FEATURE" "$SOURCE_FILE" && ! grep -q -w "$FEATURE" <<< "$DEPRECATED"; then
            SET_FLOATING_FEATURE_CONFIG "$FEATURE" "$(GET_FLOATING_FEATURE_CONFIG "$TARGET_FILE" "$FEATURE")"
        fi
    done < "$TARGET_FILE"
}

APPLY_CUSTOM_FEATURE()
{
    while IFS= read -r l; do
        [[ "$l" == "#"* ]] && continue
        [ ! "$l" ] && continue

        if [[ "$l" == "SEC_FLOATING_FEATURE_"*"="* ]]; then
            if [ ! "$(cut -d "=" -f 2- <<< "$l")" ]; then
                SET_FLOATING_FEATURE_CONFIG "$(cut -d "=" -f 1 <<< "$l")" --delete
            else
                SET_FLOATING_FEATURE_CONFIG "$(cut -d "=" -f 1 <<< "$l")" "$(cut -d "=" -f 2- <<< "$l")"
            fi
        else
            ABORT "Malformed string in ${1//$SRC_DIR\//}: \"$l\""
        fi
    done < "$1"
}
# ]

LOG_STEP_IN "- Applying target floating feature config"
APPLY_TARGET_FEATURE
LOG_STEP_OUT

if [ -f "$SRC_DIR/platform/$TARGET_PLATFORM/sff.sh" ]; then
    LOG_STEP_IN "- Applying custom platform floating feature config"
    APPLY_CUSTOM_FEATURE "$SRC_DIR/platform/$TARGET_PLATFORM/sff.sh"
    LOG_STEP_OUT
fi

if [ -f "$SRC_DIR/target/$TARGET_CODENAME/sff.sh" ]; then
    LOG_STEP_IN "- Applying custom device floating feature config"
    APPLY_CUSTOM_FEATURE "$SRC_DIR/target/$TARGET_CODENAME/sff.sh"
    LOG_STEP_OUT
fi

unset DEPRECATED BLACKLIST FALLBACK
unset -f APPLY_TARGET_FEATURE APPLY_CUSTOM_FEATURE
