#
# Copyright (C) 2025 mattchengg
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Platform configuration file for Samsung Exynos 1380 devices (s5e8835)
TARGET_BOARD_API_LEVEL=33

# Partitions
TARGET_BOOT_PARTITION_SIZE=67108864
TARGET_DTBO_PARTITION_SIZE=8388608
TARGET_VENDOR_BOOT_PARTITION_SIZE=33554432
TARGET_INIT_BOOT_PARTITION_SIZE=16777216

# Dynamic partitions
TARGET_SUPER_GROUP_NAME="group_basic"

# Dynamic partitions
TARGET_SUPER_PARTITION_SIZE=11429478400
TARGET_GROUP_BASIC_SIZE=11425284096

# OS
TARGET_OS_SINGLE_SYSTEM_IMAGE="essi"
TARGET_OS_BUILD_SYSTEM_EXT_PARTITION=false

# SEC Product Feature
TARGET_AUDIO_CONFIG_RECORDALIVE_LIB_VERSION="07010"
TARGET_AUDIO_SUPPORT_ACH_RINGTONE=false
TARGET_AUDIO_SUPPORT_DUAL_SPEAKER=true
TARGET_AUDIO_SUPPORT_VIRTUAL_VIBRATION=false
TARGET_CAMERA_SUPPORT_CAMERAX_EXTENSION=true
TARGET_CAMERA_SUPPORT_MASS_APP_FLAVOR=true
TARGET_CAMERA_SUPPORT_SDK_SERVICE=false
TARGET_COMMON_CONFIG_MDNIE_MODE="37905"
TARGET_COMMON_SUPPORT_DYN_RESOLUTION_CONTROL=false
TARGET_COMMON_SUPPORT_EMBEDDED_SIM=true
TARGET_COMMON_SUPPORT_HDR_EFFECT=false
TARGET_DVFSAPP_CONFIG_DVFS_POLICY_FILENAME="dvfs_policy_s5e8835_xx"
TARGET_FINGERPRINT_CONFIG_SENSOR="google_touch_display_optical,settings=3,no_delay_in_screen_off"
TARGET_LCD_CONFIG_COLOR_WEAKNESS_SOLUTION="0"
TARGET_LCD_CONFIG_CONTROL_AUTO_BRIGHTNESS="5"
TARGET_LCD_CONFIG_HFR_DEFAULT_REFRESH_RATE="120"
TARGET_LCD_CONFIG_HFR_MODE="2"
TARGET_LCD_CONFIG_HFR_SUPPORTED_REFRESH_RATE="60,120"
TARGET_LCD_CONFIG_SEAMLESS_BRT="149,84"
TARGET_LCD_CONFIG_SEAMLESS_LUX="300,3500"
TARGET_LCD_SUPPORT_MDNIE_HW=false
TARGET_RIL_FEATURES="onebinary satellite_carrier"
TARGET_RIL_SIM_CONFIG_MULTISIM_TRAYCOUNT="1"
TARGET_RIL_SUPPORT_WATERPROOF_SIM_TRAY_MSG=true
TARGET_WLAN_CONFIG_CONNECTION_PERSONALIZATION="0"
TARGET_WLAN_CONFIG_CPU_CSTATE_DISABLE_THRESHOLD="0"
TARGET_WLAN_CONFIG_DATA_ACTIVITY_AFFINITY_BOOSTER_THRESHOLD="0"
TARGET_WLAN_CONFIG_L1SS_DISABLE_THRESHOLD="0"
TARGET_WLAN_CONFIG_DYNAMIC_SWITCH="0"
TARGET_WLAN_SUPPORT_80211AX=true
TARGET_WLAN_SUPPORT_80211AX_6GHZ=false
TARGET_WLAN_SUPPORT_APE_SERVICE=false
TARGET_WLAN_SUPPORT_LOWLATENCY=false
TARGET_WLAN_SUPPORT_MBO=false
TARGET_WLAN_SUPPORT_MOBILEAP_5G_BASEDON_COUNTRY=true
TARGET_WLAN_SUPPORT_MOBILEAP_DUALAP=true
TARGET_WLAN_SUPPORT_MOBILEAP_OWE=false
TARGET_WLAN_SUPPORT_MOBILEAP_6G=false
TARGET_WLAN_SUPPORT_MOBILEAP_POWER_SAVEMODE=false
TARGET_WLAN_SUPPORT_MOBILEAP_PRIORITIZE_TRAFFIC=false
TARGET_WLAN_SUPPORT_MOBILEAP_WIFI_CONCURRENCY=true
TARGET_WLAN_SUPPORT_MOBILEAP_WIFISHARING_LITE=true
TARGET_WLAN_SUPPORT_SWITCH_FOR_INDIVIDUAL_APPS=true
TARGET_WLAN_SUPPORT_TWT_CONTROL=false
TARGET_WLAN_SUPPORT_WIFI_TO_CELLULAR=false
