name: 🖼️ Build Custom Runner Image

on:
  workflow_dispatch:
  
jobs:
  build-image:
    runs-on: rom4
    snapshot: 
      image-name: unica-linux
      version: 1.*
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        target: [dm2q]

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: ⚙️ Configure git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"


      - name: 🔧 Set up build environment
        run: |      
          sudo apt update
          # Install essential build tools and dependencies for Android ROM compilation
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            7zip attr ccache clang ffmpeg \
            libbrotli-dev libgtest-dev libprotobuf-dev libunwind-dev libpcre2-dev \
            libzstd-dev linux-modules-extra-$(uname -r) lld protobuf-compiler webp zram-tools
          
          # Crear/reescribir configuración de zramswap
          sudo tee /etc/default/zramswap > /dev/null <<'EOF'
          ENABLED=true
          ALGO=lz4
          SIZE=8192
          PERCENTAGE=90
          PRIORITY=1000
          EOF

          # Habilitar y arrancar el servicio
          sudo systemctl enable zramswap
          sudo systemctl restart zramswap

          # Mostrar estado
          sudo zramctl
          sudo modprobe erofs f2fs
          
      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
             
      - name: 🧹 Clean old firmware
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/cleanup.sh all 
          ./scripts/cleanup.sh fw
          ./scripts/cleanup.sh tools
          ./scripts/cleanup.sh work_dir

      - name: 🔨 Build dependencies
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/build_dependencies.sh
          
      - name: 📥 Download stock firmware
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/download_fw.sh
          
      - name: 📦 Extract stock firmware
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/extract_fw.sh
          
